services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: "gateway"

  fartdetector:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "fartdetector"

  lightlamp:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "lightlamp"
