services:
  gateway:
    image: ghcr.io/taldoflemis/badezimmer/python-services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: "gateway"

  fartdetector:
    image: ghcr.io/taldoflemis/badezimmer/python-services
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "fartdetector"

  lightlamp:
    image: ghcr.io/taldoflemis/badezimmer/python-services
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "lightlamp"

  sink:
    image: ghcr.io/taldoflemis/badezimmer/python-services
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "sink"

  toilet:
    image: ghcr.io/taldoflemis/badezimmer/python-services
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "toilet"

  waterleak:
    image: ghcr.io/taldoflemis/badezimmer/go-water-leak
    build:
      context: .
      dockerfile: Dockerfile.water-leak

  frontend:
    image: ghcr.io/taldoflemis/badezimmer/front
    build:
      context: ./badezimmer-home-page/
      dockerfile: ../Dockerfile.front
    ports:
      - "3000:3000"
