[project]
name = "badezimmer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["python-json-logger>=2.0.7"]

[tool.uv.workspace]
members = ["gateway"]
