[project]
name = "badezimmer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "protobuf>=6.33.1",
    "python-json-logger>=2.0.7",
]

[tool.uv]
package = true

[tool.uv.workspace]
members = ["gateway"]
